#!/bin/bash
. options

for f in doc/*; do
	bn=`basename $f`
	echo Transferring $bn
	. scripts/krab_start
	cat <<-qq >>$tf1
	у $bn
	и $bn
	д
	qq
	sed "s/^/@!@ /" $f >> $tf1
	cat <<-qq >>$tf1
	.кзм -@!@--
	упл
	з

	к
	qq
	cat scripts/krab_end >> $tf1
	dispak $* $tf1 > /dev/null 2>&1
done
