#!/bin/sh
. options

for f in doc/*; do
	bn=`basename $f`
	echo Transferring $bn|$conv
	. scripts/krab_start
	cat <<-qq >>$tf1
	у $bn
	и $bn
	д
	qq
	sed "s/^/@!@ /" $f >> $tf1
	cat <<-qq >>$tf1
	.кзм -@!@--
	упл
	з

	к
	qq
	cat scripts/krab_end >> $tf1
	cat $tf1|$conv>$tf2
	$b6 $* $tf2 > /dev/null 2>&1
done
